let question = [{
    "quest": "Wie viele Planeten gehören zu unserem Sonnensystem?",
    "answer_1": "6",
    "answer_2": "8",
    "answer_3": "10",
    "answer_4": "12",
    "rightanswer": 2,
}, {
    "quest": "Mit wie vielen Figuren startet ein Schachspiel?",
    "answer_1": "28",
    "answer_2": "30",
    "answer_3": "32",
    "answer_4": "34",
    "rightanswer": 3,
}, {
    "quest": "Das flächenmäßig kleinste Bundesland heißt?",
    "answer_1": "Berlin",
    "answer_2": "Bremen",
    "answer_3": "Saarland",
    "answer_4": "Hamburg",
    "rightanswer": 2,
}, {
    "quest": "Welche Gürtelfarbe existiert nicht im Kampfsport Karate?",
    "answer_1": "Schwarz",
    "answer_2": "Weiß",
    "answer_3": "Braun",
    "answer_4": "Rot",
    "rightanswer": 4,
}, {
    "quest": "Einen Feinschmecker nennt man auch?",
    "answer_1": "Gourmet",
    "answer_2": "Gourmed",
    "answer_3": "Genießer",
    "answer_4": "Leckermäulchen",
    "rightanswer": 1,
}, {
    "quest": "Welches Metall leitet Wärme am besten?",
    "answer_1": "Silber",
    "answer_2": "Kupfer",
    "answer_3": "Gold",
    "answer_4": "Aluminium",
    "rightanswer": 1,
}, {
    "quest": "Welches Vitamin wird mithilfe von Sonnenlicht im Körper gebildet?",
    "answer_1": "Vitamin C",
    "answer_2": "Vitamin E",
    "answer_3": "Vitamin D",
    "answer_4": "Vitamin A",
    "rightanswer": 3,
}, {
    "quest": "Wie vielen Zeitzonen gehört Russland an?",
    "answer_1": "5",
    "answer_2": "9",
    "answer_3": "7",
    "answer_4": "11",
    "rightanswer": 4,
}, {
    "quest": "Wie viele Bundesländer hat Deutschland?",
    "answer_1": "13",
    "answer_2": "9",
    "answer_3": "16",
    "answer_4": "20",
    "rightanswer": 3,
}, {
    "quest": "Wie viele Milchzähne bekommt ein Kind normalerweise?",
    "answer_1": "18",
    "answer_2": "32",
    "answer_3": "20",
    "answer_4": "30",
    "rightanswer": 3,
},
{
    "quest": "Wie viele Zähne hat ein erwachsener Mensch normalerweise?",
    "answer_1": "26",
    "answer_2": "30",
    "answer_3": "32",
    "answer_4": "36",
    "rightanswer": 3,
},];

// {
//     "quest": "",
//     "answer_1": "",
//     "answer_2": "",
//     "answer_3": "",
//     "answer_4": "",
//     "rightanswer": 4,
// },